import { useEffect, useMemo, useState } from "react";
import { AppWindow, Check, Copy, Loader2, X } from "lucide-react";
import { getWindowRules } from "../lib/tauri-api";
import type { AppSettings, Group, WindowRule } from "../types";

interface Props {
  groups: Group[];
  settings: AppSettings | null;
  /** Persists the tag → workspace mapping into settings. */
  onWorkspaceChange: (groupId: string, workspace: number | null) => Promise<void>;
  onClose: () => void;
}

/**
 * Two things in one place:
 *  1. The unique app-id (`--class` / `--wayland-app-id`) each profile's
 *     browser window carries, so compositors can match it.
 *  2. A tag → niri workspace mapping with a generated `window-rule` snippet.
 */
export function WindowRulesModal({ groups, settings, onWorkspaceChange, onClose }: Props) {
  const [rules, setRules] = useState<WindowRule[] | null>(null);
  const [copied, setCopied] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getWindowRules()
      .then(setRules)
      .catch((e) => setError(String(e)));
  }, []);

  const snippet = useMemo(() => {
    if (!rules || !settings) return "";
    const lines: string[] = [
      "# Generated by Multi Browser Manager",
      "# Paste these window-rule blocks into your niri config",
      "# (then run your build-config script / restart niri).",
      "",
    ];
    let any = false;
    for (const group of groups) {
      const ws = settings.groupWorkspaces[group.id];
      if (!ws) continue;
      const members = rules.filter((r) => r.groupIds.includes(group.id));
      if (members.length === 0) continue;
      lines.push(`# Tag: ${group.name} → workspace ${ws}`);
      for (const member of members) {
        lines.push("window-rule {", `    match app-id="${member.appId}"`, `    open-on-workspace ${ws}`, "}", "");
      }
      any = true;
    }
    return any ? lines.join("\n") : "";
  }, [rules, settings, groups]);

  const copy = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      setError("Clipboard unavailable");
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4">
      <div className="flex max-h-[85vh] w-full max-w-2xl flex-col rounded-xl border border-neutral-200 bg-white p-6 shadow-xl dark:border-neutral-800 dark:bg-neutral-900">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="flex items-center gap-2 text-base font-semibold">
            <AppWindow className="h-4 w-4" /> Window Rules &amp; Workspaces
          </h2>
          <button onClick={onClose} className="text-neutral-500 hover:text-neutral-700 dark:hover:text-neutral-300">
            <X className="h-5 w-5" />
          </button>
        </div>

        {!rules ? (
          <div className="flex justify-center py-10 text-neutral-400">
            <Loader2 className="h-5 w-5 animate-spin" />
          </div>
        ) : (
          <div className="flex flex-col gap-5 overflow-y-auto pr-1">
            <section>
              <h3 className="mb-2 text-sm font-semibold">App IDs</h3>
              <p className="mb-2 text-xs text-neutral-400">
                Every browser is launched with a unique <code>--class</code> /{" "}
                <code>--wayland-app-id</code>. Click an ID to copy it.
              </p>
              <div className="overflow-hidden rounded-lg border border-neutral-200 dark:border-neutral-800">
                <table className="w-full text-sm">
                  <tbody>
                    {rules.map((r) => (
                      <tr
                        key={r.profileId}
                        onClick={() => copy(r.appId, r.profileId)}
                        className="cursor-pointer border-b border-neutral-100 last:border-0 hover:bg-neutral-100 dark:border-neutral-800/60 dark:hover:bg-neutral-800/60"
                      >
                        <td className="px-3 py-2">
                          {r.profileName}
                          {r.status === "running" && (
                            <span className="ml-2 text-xs text-green-600 dark:text-green-400">● running</span>
                          )}
                        </td>
                        <td className="px-3 py-2 text-right font-mono text-xs text-neutral-500">
                          {copied === r.profileId ? (
                            <span className="inline-flex items-center gap-1 text-green-600 dark:text-green-400">
                              <Check className="h-3 w-3" /> copied
                            </span>
                          ) : (
                            r.appId
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>

            {groups.length > 0 && (
              <section>
                <h3 className="mb-2 text-sm font-semibold">Tag → niri workspace</h3>
                <p className="mb-2 text-xs text-neutral-400">
                  Assign a workspace number to a tag; the generated rules below open every
                  profile carrying that tag on that workspace. Leave empty to skip a tag.
                </p>
                <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
                  {groups.map((g) => (
                    <label key={g.id} className="flex items-center justify-between gap-2 rounded-lg border border-neutral-200 px-3 py-2 dark:border-neutral-800">
                      <span className="truncate text-sm">{g.name}</span>
                      <input
                        type="number"
                        min={1}
                        max={100}
                        value={settings?.groupWorkspaces[g.id] ?? ""}
                        onChange={(e) => {
                          const raw = e.target.value;
                          const num = raw === "" ? null : Number(raw);
                          void onWorkspaceChange(g.id, num && num >= 1 ? num : null);
                        }}
                        placeholder="—"
                        className="w-16 rounded-md border border-neutral-300 bg-white px-2 py-1 text-right text-sm outline-none focus:border-blue-600 dark:border-neutral-700 dark:bg-neutral-900"
                      />
                    </label>
                  ))}
                </div>
              </section>
            )}

            <section>
              <div className="mb-2 flex items-center justify-between">
                <h3 className="text-sm font-semibold">Generated niri rules</h3>
                {snippet && (
                  <button
                    onClick={() => copy(snippet, "snippet")}
                    className="flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs text-neutral-600 hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-800"
                  >
                    {copied === "snippet" ? (
                      <>
                        <Check className="h-3.5 w-3.5" /> Copied
                      </>
                    ) : (
                      <>
                        <Copy className="h-3.5 w-3.5" /> Copy
                      </>
                    )}
                  </button>
                )}
              </div>
              {snippet ? (
                <pre className="max-h-48 overflow-auto rounded-lg bg-neutral-100 p-3 font-mono text-xs leading-relaxed dark:bg-neutral-950">
                  {snippet}
                </pre>
              ) : (
                <p className="rounded-lg border border-dashed border-neutral-300 p-4 text-center text-xs text-neutral-400 dark:border-neutral-800">
                  Assign a workspace to a tag above to generate window rules.
                </p>
              )}
            </section>

            {error && <p className="text-sm text-red-600 dark:text-red-400">{error}</p>}
          </div>
        )}
      </div>
    </div>
  );
}
