use crate::error::{AppError, AppResult};
use std::path::{Path, PathBuf};

const KEYRING_SERVICE: &str = "multi-browser-manager";

/// OS keychain entry key for a proxy's password.
fn keyring_entry(proxy_id: &str) -> AppResult<keyring::Entry> {
    Ok(keyring::Entry::new(KEYRING_SERVICE, proxy_id)?)
}

pub fn store_proxy_password(proxy_id: &str, password: &str) -> AppResult<()> {
    let entry = keyring_entry(proxy_id)?;
    entry.set_password(password)?;
    Ok(())
}

pub fn get_proxy_password(proxy_id: &str) -> AppResult<String> {
    let entry = keyring_entry(proxy_id)?;
    match entry.get_password() {
        Ok(p) => Ok(p),
        Err(keyring::Error::NoEntry) => Ok(String::new()),
        Err(e) => Err(e.into()),
    }
}

pub fn delete_proxy_password(proxy_id: &str) -> AppResult<()> {
    let entry = keyring_entry(proxy_id)?;
    // Ignore NoEntry — deleting twice should be idempotent.
    let _ = entry.delete_credential();
    Ok(())
}

/// Directory holding per-profile proxy extension folders. Lives under the
/// user's cache dir — NOT the shared /tmp, where another user could
/// pre-create the path and redirect or read generated credential files.
pub fn extension_root() -> PathBuf {
    directories::ProjectDirs::from("com", "mbm", "Multi Browser Manager")
        .map(|dirs| dirs.cache_dir().join("proxy-ext"))
        .unwrap_or_else(|| std::env::temp_dir().join("mbm-proxy-ext"))
}

/// Generates (or regenerates) an unpacked Chrome extension that configures the
/// proxy AND injects username/password when the proxy server challenges the
/// browser. Chromium's `--proxy-server` flag cannot carry credentials, so this
/// is the only reliable way to support authenticated proxies.
///
/// Files are rewritten on every launch so credentials are always fresh, and the
/// whole directory is wiped when the profile stops.
pub fn generate_auth_proxy_extension(
    profile_id: &str,
    protocol: &str,
    host: &str,
    port: i64,
    username: &str,
    password: &str,
) -> AppResult<PathBuf> {
    let dir = extension_root().join(sanitize(profile_id));
    let scripts = dir.join("scripts");

    // Create the directory with restrictive permissions BEFORE anything is
    // written into it, so there is never a window where the credential file is
    // world-readable.
    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;
        std::fs::DirBuilder::new().mode(0o700).recursive(true).create(&scripts)?;
    }
    #[cfg(not(unix))]
    std::fs::create_dir_all(&scripts)?;

    // Note: never log credential material. Values go into the generated file only.
    let manifest = serde_json::json!({
        "manifest_version": 3,
        "name": "MBM Proxy Auth",
        "version": "1.0.0",
        "permissions": ["proxy", "webRequest", "webRequestAuthProvider"],
        "host_permissions": ["<all_urls>"],
        "background": { "service_worker": "background.js" }
    });

    // Map our protocol names to chrome.proxy scheme values.
    let scheme = match protocol {
        "socks5" => "socks5",
        _ => "http",
    };

    // Embed literals via JSON string encoding — correct for every byte
    // (quotes, backslashes, control chars, U+2028/2029) with no manual
    // escaping rules to get wrong.
    let host_js = serde_json::to_string(host)?;
    let username_js = serde_json::to_string(username)?;
    let password_js = serde_json::to_string(password)?;

    let background = format!(
        r#"// AUTO-GENERATED by Multi Browser Manager. Do not edit.
const PROXY = {{
  mode: "fixed_servers",
  rules: {{
    singleProxy: {{
      scheme: "{scheme}",
      host: {host_js},
      port: {port}
    }},
    bypassList: ["localhost", "127.0.0.1"]
  }}
}};

chrome.proxy.settings.set({{ value: PROXY, scope: "regular" }}, () => {{}});

chrome.webRequest.onAuthRequired.addListener(
  (details, asyncCallback) => {{
    asyncCallback({{
      authCredentials: {{
        username: {username_js},
        password: {password_js}
      }}
    }});
  }},
  {{ urls: ["<all_urls>"] }},
  ["asyncBlocking"]
);
"#,
        scheme = scheme,
        host_js = host_js,
        port = port,
        username_js = username_js,
        password_js = password_js,
    );

    write_private_file(&dir.join("manifest.json"), serde_json::to_string_pretty(&manifest)?)?;
    write_private_file(&dir.join("background.js"), background)?;

    Ok(dir)
}

/// Writes a file with owner-only permissions (0o600 on unix).
fn write_private_file(path: &Path, contents: String) -> AppResult<()> {
    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)?;
        f.write_all(contents.as_bytes())?;
        // Ensure the mode sticks even if the file already existed with a
        // looser mode.
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))?;
    }
    #[cfg(not(unix))]
    {
        std::fs::write(path, contents)?;
    }
    Ok(())
}

/// Removes a generated extension directory (called when the profile stops).
pub fn cleanup_extension(profile_id: &str) {
    let dir = extension_root().join(sanitize(profile_id));
    let _ = std::fs::remove_dir_all(dir);
}

/// Removes generated extension directories, EXCEPT for profiles whose browser
/// is still alive — deleting an extension under a live Chromium breaks its
/// proxy auth when the service worker reloads.
///
/// A profile is considered alive when its id is in `running_profile_ids`
/// (this session's tracked browsers) OR its DB row still says 'running' with
/// a verified live SingletonLock (orphans from a previous session; this only
/// holds on Linux, see `launcher::singleton_pid`). Everything else is swept
/// so credential files never linger on disk.
///
/// Profile ids are UUIDs (hex + '-'), which `sanitize` leaves unchanged — so
/// directory names match profile ids exactly.
pub fn cleanup_all_extensions(running_profile_ids: &[String], db: &rusqlite::Connection) {
    let root = extension_root();
    let Ok(entries) = std::fs::read_dir(&root) else {
        return; // nothing was ever generated this session
    };
    for entry in entries.flatten() {
        let dir = entry.path();
        let Some(id) = dir.file_name().map(|n| n.to_string_lossy().to_string()) else {
            continue;
        };
        let tracked = running_profile_ids.iter().any(|r| r == &id);
        let alive_by_lock = db
            .query_row(
                "SELECT user_data_dir FROM profiles WHERE id = ?1 AND status = 'running'",
                rusqlite::params![id],
                |r| r.get::<_, String>(0),
            )
            .ok()
            .map(|data_dir| {
                crate::browser::launcher::singleton_pid(std::path::Path::new(&data_dir))
                    .filter(|pid| {
                        crate::browser::launcher::pid_alive(*pid)
                            && crate::browser::launcher::pid_cmdline_contains(*pid, &data_dir)
                    })
                    .is_some()
            })
            .unwrap_or(false);
        if tracked || alive_by_lock {
            continue;
        }
        let _ = std::fs::remove_dir_all(&dir);
    }
}

fn sanitize(id: &str) -> String {
    id.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '_' })
        .collect()
}

/// Percent-encodes a URL userinfo component (proxy credentials).
fn encode_credential(s: &str) -> String {
    use percent_encoding::utf8_percent_encode;
    const CRED_SET: &percent_encoding::AsciiSet = &percent_encoding::CONTROLS
        .add(b'%')
        .add(b'@')
        .add(b':')
        .add(b'/')
        .add(b'?')
        .add(b'#')
        .add(b'[')
        .add(b']')
        .add(b'\\');
    utf8_percent_encode(s, CRED_SET).to_string()
}

/// Tests a proxy by requesting an IP-echo endpoint through it.
pub async fn test_proxy_connection(
    protocol: &str,
    host: &str,
    port: i64,
    username: Option<&str>,
    password: Option<&str>,
) -> AppResult<crate::models::proxy::ProxyTestResult> {
    let started = std::time::Instant::now();

    // SOCKS5 auth must be passed via URL credentials — reqwest's `basic_auth`
    // only works for HTTP proxies. HTTP auth still uses basic_auth().
    let has_auth = username.map(|u| !u.is_empty()).unwrap_or(false);
    let proxy_url = match protocol {
        "socks5" if has_auth => format!(
            "socks5://{}:{}@{host}:{port}",
            encode_credential(username.unwrap_or("")),
            encode_credential(password.unwrap_or(""))
        ),
        _ => format!("{protocol}://{host}:{port}"),
    };
    let mut proxy = reqwest::Proxy::all(&proxy_url)?;

    if has_auth && protocol != "socks5" {
        proxy = proxy.basic_auth(username.unwrap_or(""), password.unwrap_or(""));
    }

    let client = reqwest::Client::builder()
        .proxy(proxy)
        .timeout(std::time::Duration::from_secs(10))
        .build()?;

    match client.get("https://api.ipify.org?format=json").send().await {
        Ok(resp) => {
            let latency = started.elapsed().as_millis();
            let ip = resp
                .json::<serde_json::Value>()
                .await
                .ok()
                .and_then(|v| v.get("ip").and_then(|i| i.as_str()).map(|s| s.to_string()));

            Ok(crate::models::proxy::ProxyTestResult {
                success: true,
                message: format!("OK ({latency} ms)"),
                latency_ms: Some(latency),
                ip,
            })
        }
        Err(e) => Ok(crate::models::proxy::ProxyTestResult {
            success: false,
            message: format!("Failed: {e}"),
            latency_ms: Some(started.elapsed().as_millis()),
            ip: None,
        }),
    }
}

/// Whether a proxy protocol can be used by Chromium's `--proxy-server` flag.
pub fn is_supported_protocol(p: &str) -> bool {
    matches!(p, "http" | "socks5")
}

pub fn ensure_valid_protocol(p: &str) -> AppResult<()> {
    if is_supported_protocol(p) {
        Ok(())
    } else {
        Err(AppError::validation(format!(
            "Unsupported proxy protocol: {p} (expected http or socks5)"
        )))
    }
}

pub fn extension_dir_exists(path: &Path) -> bool {
    path.join("manifest.json").is_file() && path.join("background.js").is_file()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_extension_files() {
        let dir = generate_auth_proxy_extension(
            "test-profile-1",
            "http",
            "proxy.example.com",
            8080,
            "alice",
            "s3cr3t\"quote",
        )
        .expect("generate extension");

        assert!(extension_dir_exists(&dir));

        let bg = std::fs::read_to_string(dir.join("background.js")).unwrap();
        assert!(bg.contains(r#"host: "proxy.example.com""#));
        assert!(bg.contains(r#"port: 8080"#));
        assert!(bg.contains(r#"scheme: "http""#));
        // JSON-escaped quote must not break the JS string literal.
        assert!(bg.contains(r#"s3cr3t\"quote"#));

        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("manifest.json")).unwrap())
                .unwrap();
        assert_eq!(manifest["manifest_version"], 3);

        // Credential files must never be group/world readable.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(dir.join("background.js")).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "background.js must be 0600");
            let dir_mode = std::fs::metadata(&dir).unwrap().permissions().mode() & 0o777;
            assert_eq!(dir_mode, 0o700, "extension dir must be 0700");
        }

        cleanup_extension("test-profile-1");
        assert!(!dir.exists());
    }

    #[test]
    fn escapes_control_characters_via_json() {
        // Tab/newline/backslash in a password must still produce valid JS.
        let dir = generate_auth_proxy_extension(
            "test-profile-2",
            "http",
            "h",
            1,
            "u\tser",
            "p\u{7}\"ss\n\\w",
        )
        .expect("generate extension");
        let bg = std::fs::read_to_string(dir.join("background.js")).unwrap();
        // serde_json escapes these; the file must remain parseable as JS
        // literals (no raw control bytes in the string literals).
        assert!(!bg.contains("p\u{7}"));
        assert!(bg.contains(r"p\u0007") || bg.contains(r"p\a") || bg.contains("\\u0007"));
        cleanup_extension("test-profile-2");
    }

    #[test]
    fn protocol_validation() {
        assert!(ensure_valid_protocol("http").is_ok());
        assert!(ensure_valid_protocol("socks5").is_ok());
        assert!(ensure_valid_protocol("ftp").is_err());
    }

    #[test]
    fn sanitizes_profile_ids() {
        assert_eq!(sanitize("a/b c"), "a_b_c");
    }
}
